// Mocks generated by Mockito 5.4.5 from annotations
// in tanami_capital_task/test/features/login_feature/presentation/login_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:flutter/material.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;
import 'package:multiple_result/multiple_result.dart' as _i7;
import 'package:tanami_capital_task/app_core/routes/nav_service.dart' as _i12;
import 'package:tanami_capital_task/app_core/storage/storage_repo.dart' as _i13;
import 'package:tanami_capital_task/app_core/unit/failures.dart' as _i9;
import 'package:tanami_capital_task/app_core/unit/usecase.dart' as _i16;
import 'package:tanami_capital_task/features/initializer_feature/data/repos/countries_repo.dart'
    as _i4;
import 'package:tanami_capital_task/features/initializer_feature/data/respone_models/country_model.dart'
    as _i15;
import 'package:tanami_capital_task/features/initializer_feature/domain/usecases/get_countries_use_case.dart'
    as _i14;
import 'package:tanami_capital_task/features/login_feature/data/repos/login_repo.dart'
    as _i2;
import 'package:tanami_capital_task/features/login_feature/data/respone_models/user_model.dart'
    as _i8;
import 'package:tanami_capital_task/features/login_feature/domain/request_models/login_request_model.dart'
    as _i10;
import 'package:tanami_capital_task/features/login_feature/domain/usecases/login_use_case.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLoginRepo_0 extends _i1.SmartFake implements _i2.LoginRepo {
  _FakeLoginRepo_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGlobalKey_1<T extends _i3.State<_i3.StatefulWidget>>
    extends _i1.SmartFake
    implements _i3.GlobalKey<T> {
  _FakeGlobalKey_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCountriesRepo_2 extends _i1.SmartFake implements _i4.CountriesRepo {
  _FakeCountriesRepo_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [LoginUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginUseCase extends _i1.Mock implements _i5.LoginUseCase {
  MockLoginUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.LoginRepo get loginRepo =>
      (super.noSuchMethod(
            Invocation.getter(#loginRepo),
            returnValue: _FakeLoginRepo_0(this, Invocation.getter(#loginRepo)),
          )
          as _i2.LoginRepo);

  @override
  _i6.Future<_i7.Result<_i8.UserModel?, _i9.Failure>> call(
    _i10.LoginRequestModel? requestModel,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [requestModel]),
            returnValue:
                _i6.Future<_i7.Result<_i8.UserModel?, _i9.Failure>>.value(
                  _i11.dummyValue<_i7.Result<_i8.UserModel?, _i9.Failure>>(
                    this,
                    Invocation.method(#call, [requestModel]),
                  ),
                ),
          )
          as _i6.Future<_i7.Result<_i8.UserModel?, _i9.Failure>>);
}

/// A class which mocks [NavService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNavService extends _i1.Mock implements _i12.NavService {
  MockNavService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.GlobalKey<_i3.NavigatorState> get navKey =>
      (super.noSuchMethod(
            Invocation.getter(#navKey),
            returnValue: _FakeGlobalKey_1<_i3.NavigatorState>(
              this,
              Invocation.getter(#navKey),
            ),
          )
          as _i3.GlobalKey<_i3.NavigatorState>);

  @override
  bool isCurrent(String? newRoute) =>
      (super.noSuchMethod(
            Invocation.method(#isCurrent, [newRoute]),
            returnValue: false,
          )
          as bool);

  @override
  void setCurrent(String? newRoute) => super.noSuchMethod(
    Invocation.method(#setCurrent, [newRoute]),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<dynamic> pushNamed(String? routeName, {Object? arguments}) =>
      (super.noSuchMethod(
            Invocation.method(#pushNamed, [routeName], {#arguments: arguments}),
            returnValue: _i6.Future<dynamic>.value(),
          )
          as _i6.Future<dynamic>);

  @override
  _i6.Future<dynamic> pushReplacementNamed(
    String? routeName, {
    Object? arguments,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #pushReplacementNamed,
              [routeName],
              {#arguments: arguments},
            ),
            returnValue: _i6.Future<dynamic>.value(),
          )
          as _i6.Future<dynamic>);

  @override
  _i6.Future<dynamic> pushNamedAndRemoveUntil(
    String? routeName, {
    Object? arguments,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #pushNamedAndRemoveUntil,
              [routeName],
              {#arguments: arguments},
            ),
            returnValue: _i6.Future<dynamic>.value(),
          )
          as _i6.Future<dynamic>);

  @override
  _i6.Future<dynamic> push(_i3.Widget? screen) =>
      (super.noSuchMethod(
            Invocation.method(#push, [screen]),
            returnValue: _i6.Future<dynamic>.value(),
          )
          as _i6.Future<dynamic>);

  @override
  _i6.Future<dynamic> pushAndRemoveUntil(_i3.Widget? screen) =>
      (super.noSuchMethod(
            Invocation.method(#pushAndRemoveUntil, [screen]),
            returnValue: _i6.Future<dynamic>.value(),
          )
          as _i6.Future<dynamic>);

  @override
  void pop() => super.noSuchMethod(
    Invocation.method(#pop, []),
    returnValueForMissingStub: null,
  );

  @override
  bool canPop() =>
      (super.noSuchMethod(Invocation.method(#canPop, []), returnValue: false)
          as bool);
}

/// A class which mocks [StorageRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageRepo extends _i1.Mock implements _i13.StorageRepo {
  MockStorageRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<String?> read(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#read, [key]),
            returnValue: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<void> write({required String? key, required String? value}) =>
      (super.noSuchMethod(
            Invocation.method(#write, [], {#key: key, #value: value}),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> delete(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [key]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deleteAll() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAll, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<bool> isContains(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#isContains, [key]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);
}

/// A class which mocks [GetCountriesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCountriesUseCase extends _i1.Mock
    implements _i14.GetCountriesUseCase {
  MockGetCountriesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.CountriesRepo get countriesRepo =>
      (super.noSuchMethod(
            Invocation.getter(#countriesRepo),
            returnValue: _FakeCountriesRepo_2(
              this,
              Invocation.getter(#countriesRepo),
            ),
          )
          as _i4.CountriesRepo);

  @override
  _i6.Future<_i7.Result<List<_i15.CountryModel>, _i9.Failure>> call(
    _i16.NoParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i6.Future<
              _i7.Result<List<_i15.CountryModel>, _i9.Failure>
            >.value(
              _i11.dummyValue<_i7.Result<List<_i15.CountryModel>, _i9.Failure>>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i6.Future<_i7.Result<List<_i15.CountryModel>, _i9.Failure>>);
}
