// Mocks generated by Mockito 5.4.5 from annotations
// in tanami_capital_task/test/features/login_feature/domain/usecases/login_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:multiple_result/multiple_result.dart' as _i4;
import 'package:tanami_capital_task/app_core/unit/failures.dart' as _i6;
import 'package:tanami_capital_task/features/login_feature/data/repos/login_repo.dart'
    as _i2;
import 'package:tanami_capital_task/features/login_feature/data/respone_models/user_model.dart'
    as _i5;
import 'package:tanami_capital_task/features/login_feature/domain/request_models/login_request_model.dart'
    as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [LoginRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginRepo extends _i1.Mock implements _i2.LoginRepo {
  MockLoginRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i5.UserModel?, _i6.Failure>> login(
    _i7.LoginRequestModel? requestModel,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#login, [requestModel]),
            returnValue:
                _i3.Future<_i4.Result<_i5.UserModel?, _i6.Failure>>.value(
                  _i8.dummyValue<_i4.Result<_i5.UserModel?, _i6.Failure>>(
                    this,
                    Invocation.method(#login, [requestModel]),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<_i5.UserModel?, _i6.Failure>>);
}
